#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the breakingRecords function below.
def breakingRecords(scores):
    maxi=scores[0]
    mini=scores[0]
    a=0
    b=0
    
    for i in range(1,n):
       
        if scores[i]>maxi:
            a+=1
            maxi=scores[i]
        elif scores[i]<mini:
            b+=1
            mini=scores[i]
    return a,b
            

if __name__ == '__main__':
    #fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)
    print(*result,end='')

   # fptr.write(' '.join(map(str, result)))
    #fptr.write('\n')

    #fptr.close()
