#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the kangaroo function below.
def kangaroo(x1, v1, x2, v2):
    sum1=x1
    sum2=x2
    if (x2>x1 and v2>=v1) or (x2-x1)%(v1-v2)!=0:
        return print("NO")
    else:
        return print("YES")

if __name__ == '__main__':
    

    x1V1X2V2 = input().split()

    x1 = int(x1V1X2V2[0])

    v1 = int(x1V1X2V2[1])

    x2 = int(x1V1X2V2[2])

    v2 = int(x1V1X2V2[3])


    result = kangaroo(x1, v1, x2, v2)

    
